apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: registration-app
  ports:
    - protocol: TCP
      port: 80  # External access port
      targetPort: 5000  # Port inside the container
  type: NodePort  # Exposes service outside Minikube
